In [1]:
import pandas as pd
import glob

In [2]:
input_path = "C:/Users/USER/google-search-console/date-page-query/*.csv"
file_list = [f for f in glob.glob(input_path)]
file_list

['C:/Users/USER/google-search-console/date-page-query\\uk-2022-12-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\uk-2023-01-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\uk-2023-02-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\uk-2023-03-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\uk-2023-04-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\uk-2023-05-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\uk-2023-06-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\uk-2023-07-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\uk-2023-08-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\uk-2023-09-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\uk-2023-10-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\uk-2023-11-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\uk-2023-12-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\uk-2024-01-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\uk-2024-02-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\us-2022-12-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\us-2023-01-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\us-2023-02-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\us-2023-03-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\us-2023-04-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\us-2023-05-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\us-2023-06-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\us-2023-07-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\us-2023-08-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\us-2023-09-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\us-2023-10-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\us-2023-11-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\us-2023-12-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\us-2024-01-01-date-page-query.csv',
 'C:/Users/USER/google-search-console/date-page-query\\us-2024-02-01-date-page-query.csv']

In [3]:
total = pd.DataFrame()

for file in file_list:
    temp = pd.read_csv(file, parse_dates=['date'])
    total = pd.concat([total, temp])

total['sitecode'] = total['website'].str.split("/", expand=True)[3]

kw_set = pd.read_csv('prime-keyword-set-raw-v1.0-20240402.csv')

total_merge_outer = total.merge(kw_set, how = 'outer', left_on = ['sitecode', 'query'], right_on = ['sitecode', 'KEYWORDS'])

total_merge_outer["Global Annual"] = total_merge_outer["Global Annual"].fillna(0)
total_merge_outer["Global Average Monthly"] = total_merge_outer["Global Average Monthly"].fillna(0)
total_merge_outer["Country Annual"] = total_merge_outer["Country Annual"].fillna(0)
total_merge_outer["Country Average Monthly"] = total_merge_outer["Country Average Monthly"].fillna(0)

total_merge_outer["Global Annual"] = total_merge_outer["Global Annual"].astype(int)
total_merge_outer["Global Average Monthly"] = total_merge_outer["Global Average Monthly"].astype(int)
total_merge_outer["Country Annual"] = total_merge_outer["Country Annual"].astype(int)
total_merge_outer["Country Average Monthly"] = total_merge_outer["Country Average Monthly"].astype(int)

total_merge_outer.to_csv('total_merge_outer.csv')

total_merge_outer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29797737 entries, 0 to 29797736
Data columns (total 26 columns):
 #   Column                   Dtype
---  ------                   -----
 0   date                     datetime64[ns]
 1   page                     object
 2   query                    object
 3   clicks                   float64
 4   impressions              float64
 5   ctr                      float64
 6   position                 float64
 7   website                  object
 8   sitecode                 object
 9   Keyword Set              object
 10  Models                   object
 11  Strategic Topics         object
 12  Rising Topics            object
 13  CEJ                      object
 14  Channel                  object
 15  Page Type                object
 16  Topic Depth1             object
 17  Topic Depth2             object
 18  Topic Depth3             object
 19  Topic Depth4             object
 20  Generic/Branded          object
 21  KEYWORDS                 object
 22  Global Annual            int32
 23  Global Average Monthly   int32
 24  Country Annual           int32
 25  Country Average Monthly  int32
dtypes: datetime64[ns](1), float64(4), int32(4), object(17)
memory usage: 5.3+ GB

In [6]:
total_merge_left = total.merge(kw_set, how = 'left', left_on = ['sitecode', 'query'], right_on = ['sitecode', 'KEYWORDS'])
total_merge_left.to_csv('total_merge_left.csv')

total_merge_left.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29794171 entries, 0 to 29794170
Data columns (total 26 columns):
 #   Column                   Dtype
---  ------                   -----
 0   date                     datetime64[ns]
 1   page                     object
 2   query                    object
 3   clicks                   int64
 4   impressions              int64
 5   ctr                      float64
 6   position                 float64
 7   website                  object
 8   sitecode                 object
 9   Keyword Set              object
 10  Models                   object
 11  Strategic Topics         object
 12  Rising Topics            object
 13  CEJ                      object
 14  Channel                  object
 15  Page Type                object
 16  Topic Depth1             object
 17  Topic Depth2             object
 18  Topic Depth3             object
 19  Topic Depth4             object
 20  Generic/Branded          object
 21  KEYWORDS                 object
 22  Global Annual            float64
 23  Global Average Monthly   float64
 24  Country Annual           float64
 25  Country Average Monthly  float64
dtypes: datetime64[ns](1), float64(6), int64(2), object(17)
memory usage: 5.8+ GB

In [9]:
check = pd.read_csv("C:/Users/USER/gsc-prime-kw-set-merge/total_merge_outer.csv")
check.head()

C:\Users\USER\AppData\Local\Temp\ipykernel_3440\1482740145.py:1: DtypeWarning: Columns (10,11,12,13,14,15,16,17,18,19,20,21,22) have mixed types. Specify dtype option on import or set low_memory=False.
  check = pd.read_csv("C:/Users/USER/gsc-prime-kw-set-merge/total_merge_outer.csv")

,Unnamed: 0,date,page,query,clicks,impressions,ctr,position,website,sitecode,...,Topic Depth1,Topic Depth2,Topic Depth3,Topic Depth4,Generic/Branded,KEYWORDS,Global Annual,Global Average Monthly,Country Annual,Country Average Monthly
0,0,2023-08-04,https://www.samsung.com/uk/support/mobile-devi...,"""bixby""",1.0,2.0,0.5,1.0,https://www.samsung.com/uk/,uk,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2023-11-10,https://www.samsung.com/uk/offer/black-friday/,"""black friday""",1.0,2.0,0.5,53.5,https://www.samsung.com/uk/,uk,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,2023-08-06,https://www.samsung.com/uk/support/mobile-devi...,"""can't connect"" https://news.google.com",1.0,1.0,1.0,20.0,https://www.samsung.com/uk/,uk,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,2022-12-02,https://www.samsung.com/uk/support/mobile-devi...,"""device overheating"" message and apps closing",1.0,1.0,1.0,2.0,https://www.samsung.com/uk/,uk,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2022-12-05,https://www.samsung.com/uk/support/mobile-devi...,"""device overheating"" message and apps closing",1.0,1.0,1.0,2.0,https://www.samsung.com/uk/,uk,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
check["Global Annual"] = check["Global Annual"].fillna(0)
check["Global Average Monthly"] = check["Global Average Monthly"].fillna(0)
check["Country Annual"] = check["Country Annual"].fillna(0)
check["Country Average Monthly"] = check["Country Average Monthly"].fillna(0)
check.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29797737 entries, 0 to 29797736
Data columns (total 27 columns):
 #   Column                   Dtype
---  ------                   -----
 0   Unnamed: 0               int64
 1   date                     object
 2   page                     object
 3   query                    object
 4   clicks                   float64
 5   impressions              float64
 6   ctr                      float64
 7   position                 float64
 8   website                  object
 9   sitecode                 object
 10  Keyword Set              object
 11  Models                   object
 12  Strategic Topics         object
 13  Rising Topics            object
 14  CEJ                      object
 15  Channel                  object
 16  Page Type                object
 17  Topic Depth1             object
 18  Topic Depth2             object
 19  Topic Depth3             object
 20  Topic Depth4             object
 21  Generic/Branded          object
 22  KEYWORDS                 object
 23  Global Annual            float64
 24  Global Average Monthly   float64
 25  Country Annual           float64
 26  Country Average Monthly  float64
dtypes: float64(8), int64(1), object(18)
memory usage: 6.0+ GB

In [19]:
check["Global Annual"] = check["Global Annual"].astype(int)
check["Global Average Monthly"] = check["Global Average Monthly"].astype(int)
check["Country Annual"] = check["Country Annual"].astype(int)
check["Country Average Monthly"] = check["Country Average Monthly"].astype(int)

In [20]:
check.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29797737 entries, 0 to 29797736
Data columns (total 27 columns):
 #   Column                   Dtype
---  ------                   -----
 0   Unnamed: 0               int64
 1   date                     object
 2   page                     object
 3   query                    object
 4   clicks                   float64
 5   impressions              float64
 6   ctr                      float64
 7   position                 float64
 8   website                  object
 9   sitecode                 object
 10  Keyword Set              object
 11  Models                   object
 12  Strategic Topics         object
 13  Rising Topics            object
 14  CEJ                      object
 15  Channel                  object
 16  Page Type                object
 17  Topic Depth1             object
 18  Topic Depth2             object
 19  Topic Depth3             object
 20  Topic Depth4             object
 21  Generic/Branded          object
 22  KEYWORDS                 object
 23  Global Annual            int32
 24  Global Average Monthly   float64
 25  Country Annual           float64
 26  Country Average Monthly  float64
dtypes: float64(7), int32(1), int64(1), object(18)
memory usage: 5.9+ GB